version: "2"

services:
  nginx:
    build:
      context: ./
    container_name: strix-backend
    environment:
      MONGODB_URI: 'mongodb+srv://root:qKFwQSvHPMsGfPZY@cluster1.m1imnkx.mongodb.net/StrixTestDB'
      CORS_WHITELIST: ''
      DRUID_BROKER: "http://192.168.243.128:8082/druid/v2/?pretty"
    ports:
      - 8000:3001

